title: 散事记文
description: 一些杂文，杂事，杂东西
google_analytics: [UA-138453736-2]

github_username: jaklerluo
repository: "jaklerluo/jaklerluo.github.io"

plugins:
  - jekyll-feed

theme: jekyll-theme-architect
